
# Nathan Anderson-Hobbs

## Visual Analytics

## Exercises 1-5



### Exercise 1

```{r}
link='https://github.com/EvansDataScience/data/raw/master/eduwa.rda'

load(file=url(link))
```

```{r}
library(ggplot2)

absoluteT=table(eduwa$LocaleType,exclude = 'nothing')
ToPlot=prop.table(absoluteT)
names(ToPlot)[5]='Unknown'

tableFreq=as.data.frame(ToPlot)
names(tableFreq)=c("locale","pct")
tableFreq$pct <- tableFreq$pct*100 
tableFreq$locale <- factor(tableFreq$locale, levels = tableFreq$locale[order(-tableFreq$pct)])


tableFreqO=tableFreq[order(tableFreq$pct),]

base= ggplot(data = tableFreqO, 
             aes(x = locale,
                 y = pct)) 

library(colorspace)

plot1 = base + geom_bar(fill = 'gray50',
                        stat = 'identity') + scale_x_discrete(limits=tableFreqO$locale) 

titleText2 = 'Are all locations getting a fair share of public schools in WA?'
sourceText = "Source: US Department of Education"

ytext = "Share of WA public schools"

plot2 = plot1 + labs(title=titleText2,
                     x =NULL, 
                     y = ytext,
                     caption = sourceText)

plot3 = plot2 + geom_hline(yintercept = 25,
                           linetype="dashed", 
                           size=1,
                           alpha=0.3)
library(scales)

plot4 = plot3 + scale_y_continuous(breaks=c(0,10, 25,40,50),
                                 limits = c(0, 50),
                                 labels=scales::unit_format(suffix = '%')) 

plot5 = plot4 + theme(panel.background = element_rect(fill = "white",
                                                    colour = "grey50",
                                                    linetype = 'blank'),
                    axis.line.x.bottom = (element_line(linetype = 'solid')),
                    axis.ticks.y = (element_line(linetype = "blank")),
                    axis.text = (element_text(colour = 'gray25')),
                    axis.title.x = (element_text(colour = 'gray25',
                                                 size = 9,
                                                 margin=unit(c(0.25,0,0,0), 'cm'))),
                    plot.caption = element_text(hjust = 1,
                                                colour = 'gray25',
                                                size = 7),
                    plot.title = element_text(hjust = 0, 
                                              colour = "gray25", 
                                              face = "bold", 
                                              size = 14,
                                              margin=unit(c(0,0,.5,0),"cm")),
                    plot.margin = unit(c(.75,1,0.25,.5),'cm'))
                   
plot6 = plot5 + geom_text(aes(y = pct ,
                            label = paste0(round(pct,2), '%')),
                        hjust=-0.2,
                        size = 2.5)

plot7 = plot6 + coord_flip() 

plot7
```


### Exercise 2

```{r}
tableFreqO=tableFreq[order(tableFreq$pct),]
tableFreqO$gap=tableFreqO$pct-25

tableFreqO$PositiveGap=ifelse(tableFreqO$gap>0,T,F)

base = ggplot(tableFreqO, aes(locale,gap,color=PositiveGap,
                              label = round(gap,3)))
lolliplot1=base + geom_segment(aes(y = 0, 
                                   x = locale, 
                                   yend = gap, 
                                   xend = locale), color = "gray") 
lolliplot2=lolliplot1 + geom_point() 

lolliplot3= lolliplot2 + scale_x_discrete(limits=tableFreqO$locale) 


lolliplot4 = lolliplot3 + geom_text(nudge_x=0.3) 

lolliplot5 =lolliplot4 + labs(title="Greater or less than 25%?",
                              subtitle = "Distribution of schools among locales",
                     x = NULL, 
                     y = "Gap (relative to 25%)",
                     caption = sourceText)

lolliplot6 = lolliplot5 + theme(panel.background = element_rect(fill = "white",
                                                    color = 'gray25'),
                                plot.title = element_text(colour='gray25',
                                                     size = 15,
                                                     face = 'bold'),
                                plot.margin = unit(c(.5,1,0,1.25),'cm'),
                                axis.ticks = element_blank(),
                                axis.text.y = element_blank(),
                                plot.caption = element_text(colour = 'gray25',
                                                            hjust = 1,
                                                            size = 7,
                                                            margin=unit(c(.5,0,.5,.5),'cm')),
                                legend.title = element_text())



lolliplot7 = lolliplot6 + coord_cartesian(ylim = c(-25, 15)) + geom_hline(yintercept = 0,
           linetype="dashed",
           size=1,
           alpha=0.3)

lolliplot7
```

### Exercise 3

```{r}
frqTabO=as.data.frame(prop.table(table(eduwa$High.Grade)))
names(frqTabO)=c('grade','pct')

base = ggplot(frqTabO,aes(x=grade,y=percent))
box1 = ggplot(eduwa, aes(y=as.numeric(High.Grade))) 
box1 = box1 + geom_boxplot(color = 'black', fill='white') + coord_flip()
ordLabels= levels(eduwa$High.Grade)
box2 = box1 + scale_y_continuous(labels=ordLabels,breaks=1:15)
library(colorspace)
ordLabels= levels(eduwa$High.Grade)
titleText='Half of all schools offer up to 8th grade'
titleText4 = 'Washington Public Schools'
box3 = box2 + labs(title=titleText,
                   subtitle =titleText4,
                   caption="Source: US Department of Education",
                   xlab=NULL)
box4 = box3 + theme(plot.margin = unit(c(1,1.5,1,1.5), 'cm'),
                    text = element_text(colour = 'gray25'),
             plot.title = element_text(hjust=0.5,
                                       face = 'bold',
                                  size = 15),
             plot.caption = element_text(size = 8),
             plot.subtitle = element_text(hjust=0.5),
             panel.background = element_rect(fill = 'white'),
             axis.ticks = (element_line(linetype = "blank")),
             axis.text.y = element_blank(),
             axis.title.x = element_blank())
box4 + scale_x_continuous(limits=c(-.75,.75)) 

```

### Exercise 4

```{r}
eduwaFL <- eduwa[complete.cases(eduwa$Free.Lunch),]

base= ggplot(eduwaFL,aes(x = Free.Lunch))  

h1= base + geom_histogram(binwidth = 100,boundary=0, color='black', fill='white')


h1= h1 + stat_bin(binwidth = 100, aes(label=..count..), 
                  geom = "text",boundary = 0,vjust=-0.5)

h1 = h1 + labs(title="Most schools have fewer than 500 students receiving free lunch",
               caption="Source: US Department of Education",
               y = "Number of Schools",
               x = "Students Receiving Free Lunches")

h1 = h1 + theme(plot.margin = unit(c(.75,1,.5,.5), 'cm'),
                text = element_text(colour = 'gray25'),
                plot.title = element_text(hjust=0.5,
                                          size = 15,
                                          face='bold'),
                plot.caption = element_text(size=7),
                 panel.background = element_rect(fill = 'white'),
                axis.ticks.y = element_blank(),
                axis.text.y=element_blank())
                


h1 = h1 + coord_cartesian(ylim = c(0, 1000)) 

h1 + scale_x_continuous(breaks=c(0,250,500,750,1000,1250,1500,1750,1000),
                        limits=c(0,2000)) + geom_vline(xintercept = 500,
           linetype="dashed",
           size=1,
           alpha=0.3)
```

### Exercise 5

```{r}
eduwa4=eduwa[complete.cases(eduwa$Student.Teacher.Ratio),]

meanValues=tapply(eduwa4$Student.Teacher.Ratio, 
                  eduwa4$County, 
                  mean)
df <- as.data.frame(meanValues)
df$county <- rownames(df)

base = ggplot(df, aes(x = meanValues))

hist1 = base + geom_histogram(binwidth=2, boundary = 0, color='black', fill='white')

hist1 = hist1 + geom_vline(aes(xintercept=mean(meanValues)),
            color="gray50", linetype="dashed", size=1)

hist1 = hist1 + labs(title="WA counties usually have between 18-20 students per teacher on average",
                     x = "Average Student-Teacher Ratio",
                     y = "Number of Counties",
                     caption = "Source: US Department of Education")

hist1 = hist1 + scale_x_continuous(breaks=c(10,12,14,16,18,20,22,24)) + scale_y_continuous(limits=c(0,20)) 

hist1 = hist1 + stat_bin(binwidth = 2, aes(label=..count..), 
                  geom = "text",boundary = 0,vjust=-0.5)

hist1 + theme(panel.background = element_rect(fill="white", color='black'),
              plot.margin = unit(c(1,1,.5,1),'cm'),
              plot.title = element_text(color='gray25',
                                        face='bold',
                                        hjust=.5),
              plot.caption = element_text(size=7),
              axis.text.y = element_blank(),
              axis.ticks.y = element_blank())

```

```{r}
df2 <- as.data.frame(meanValues)
df2$county <- rownames(df2)

base = ggplot(df2, aes(x = meanValues))

dens1 = base + geom_density()

dens1 = dens1 + geom_vline(aes(xintercept=mean(meanValues)),
            color="gray50", linetype="dashed", size=1)

dens1 = dens1 + labs(title="WA counties usually have between 18-20 students per teacher on average",
                     x = "Average Student-Teacher Ratio",
                     y = "Number of Counties",
                     caption = "Source: US Department of Education")

dens1 = dens1 + theme(panel.background = element_rect(fill='white', color = 'black'),
                      plot.margin = unit(c(.5,1,.5,.5),'cm'),
                      text = element_text(color='gray25'),
                      plot.title = element_text(face='bold',
                                                hjust=.5),
                      plot.caption = element_text(size=7))

dens1 = dens1 + scale_x_continuous(breaks=c(10,12,14,16,18,20,22,24)) 
                                    

dens1 + scale_y_continuous(breaks=c(0,.05,.1,.15,.2), labels = c('0','5','10','15','20'), limits=c(0,.2))
              
```

