
2. Visualization for ordinal scales


```{r}
link='https://github.com/EvansDataScience/data/raw/master/eduwa.rda'

#getting the data TABLE from the file in the cloud:
load(file=url(link))
```

```{r}
base = ggplot(frqTabO,aes(x=grade,y=percent))

box1 = ggplot(eduwa, aes(y=as.numeric(High.Grade))) 

box1 = box1 + geom_boxplot(fill='white') + coord_flip()

ordLabels= levels(eduwa$High.Grade)

box2 = box1 + scale_y_continuous(labels=ordLabels,breaks=1:15)

library(colorspace)

ordLabels= levels(eduwa$High.Grade)

titleText='Highest Grade Offered'
titleText4 = 'Washington Public Schools'
SourceText1 = 'Source: Unknown'


box3 = box2 + labs(title=titleText,
                   subtitle =titleText4,
                   caption=SourceText1,
                   xlab=NULL)

box4 = box3 + theme(plot.margin = unit(c(1,1.5,1,1.5), 'cm'),
                    text = element_text(colour = 'gray25'),
             plot.title = element_text(hjust=0.5,
                                       face = 'bold',
                                  size = 15),
             plot.caption = element_text(size = 8),
             plot.subtitle = element_text(hjust=0.5),
             panel.background = element_rect(fill = 'white'),
             axis.ticks = (element_line(linetype = "blank")),
             axis.text.y = element_blank(),
             axis.title.x = element_blank())



box4 + scale_x_continuous(limits=c(-0.75,.75))



```


